New banner for Community Day
Signalen/signalen.org pull request #65
Opened 2021-02-26 15:03 UTC by AlbaRoza

Temporary banner until the community day happens (22nd of March)

2021-02-26 15:12 UTC, AlbaRoza reviewed
Link changed

2021-03-01 09:50 UTC, felixfaassen requested changes
Refer to the correct variable name to refer to city.png

2021-03-01 09:50 UTC, felixfaassen commented on src/components/Payoff/index.en.js
> +      <ResponsiveImage src={city} alt="City with construction workers, people walking by and a hadicapped man" />
@AlbaRoza great PR! There is one small problem. You are referencing a variable {city} which does not exist and will break the build. Consider changing either line 4 with `import missedChances` to `import city` OR chance in this line {city} to {missedChances}. If you need help let me know.

2021-03-01 10:00 UTC, felixfaassen commented on src/components/Payoff/index.en.js
> +      <ResponsiveImage src={city} alt="City with construction workers, people walking by and a hadicapped man" />
@AlbaRoza I made the changes for you.

2021-03-01 10:01 UTC, felixfaassen submitted a review, later dismissed

2021-03-01 16:12 UTC, felixfaassen commented
@AlbaRoza and I decided to go for the solution provided by @bartjkdp . Thanks for the work @AlbaRoza

2021-03-01 16:12 UTC, closed without merging